# Generated by Django 4.1.5 on 2023-01-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background_type',
            field=models.CharField(choices=[('primary', 'primary'), ('secondry', 'secondry'), ('danger', 'danger')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='plan_type',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('POPULAR', 'POPULAR'), ('ENTERPRISE', 'ENTERPRISE')], max_length=30),
        ),
    ]
