# Generated by Django 4.1.5 on 2023-01-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_orderitem_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
