# Generated by Django 4.1.5 on 2023-01-21 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
