# Generated by Django 4.1.5 on 2023-01-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_orderitem_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='created_on',
        ),
    ]
