# Generated by Django 4.1.5 on 2023-01-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_orderitem_options_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
