# Generated by Django 4.1.5 on 2023-01-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_orderitem_options_orderitem_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-updated_on', '-created_on']},
        ),
    ]
