# Generated by Django 4.1.5 on 2023-01-21 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_orderitem_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
