# Generated by Django 4.1.5 on 2023-02-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_plan_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_on', 'added_on']},
        ),
    ]
