# Generated by Django 4.1.5 on 2023-02-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_linkedin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkedin',
            options={'ordering': ['-updated_on', '-created_on']},
        ),
        migrations.AddField(
            model_name='linkedin',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
