# Generated by Django 4.1.5 on 2023-02-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_linkedin_options_linkedin_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedin',
            name='resume',
            field=models.FileField(upload_to=''),
        ),
    ]
