# Generated by Django 4.1.5 on 2023-02-16 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_linkedin_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedin',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin', to='products.product'),
        ),
    ]
