# Generated by Django 4.1.5 on 2023-02-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_linkedin_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='authorized',
            field=models.BooleanField(choices=[('YES', 'YES'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='sponsorship',
            field=models.BooleanField(choices=[('YES', 'YES'), ('NO', 'NO')]),
        ),
    ]
