# Generated by Django 4.1.5 on 2023-02-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_client_authorized_alter_client_sponsorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='authorized',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='sponsorship',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
