# Generated by Django 4.1.5 on 2023-02-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='resume',
            field=models.FileField(upload_to='resumes'),
        ),
    ]
