# Generated by Django 4.1.5 on 2023-02-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_client_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-updated_on', '-created_on'], 'verbose_name_plural': 'Client Forms'},
        ),
    ]
